KAMUS_EKSPANSI = {
    "natural language processing": ["nlp", "text mining", "bert", "word2vec", "embedding", "sentiment analysis"],
    "nlp": ["text mining", "bert", "word2vec", "embedding", "sentiment analysis", "natural language processing"],
    "sentence-bert": ["sbert", "bert", "embedding", "nlp", "semantic"],
    "bm25": ["tf-idf", "term frequency", "information retrieval", "lexical"],
    "deep learning": ["cnn", "rnn", "lstm", "transformer", "bert", "mobilenet", "dl", "neural network", "jaringan saraf tiruan"],
    "machine learning": ["ml", "supervised", "unsupervised", "klasifikasi", "regresi", "clustering", "svm", "random forest", "decision tree"],
    "decision support system": ["dss", "spk", "ahp", "topsis", "saw", "moora", "sistem pendukung keputusan", "vikor", "promethee"],
    "spk": ["dss", "ahp", "topsis", "saw", "moora", "sistem pendukung keputusan", "vikor", "promethee"],
    "ahp": ["analytical hierarchy process", "dss", "spk", "pembobotan"],
    "topsis": ["dss", "spk", "preferensi"],
    "computer vision": ["cv", "image processing", "pengolahan citra", "object detection", "yolo", "segmentasi"],
    "yolov8": ["yolo", "object detection", "computer vision", "cnn"],
    "internet of things": ["iot", "sensor", "arduino", "raspberry", "smart home", "mikrokontroler", "nodemcu", "mqtt", "esp32"],
    "iot": ["sensor", "arduino", "raspberry", "smart home", "mikrokontroler", "nodemcu", "mqtt", "esp32", "internet of things"],
    "esp32": ["iot", "mikrokontroler", "arduino", "sensor", "nodemcu"],
    "software engineering": ["rpl", "agile", "scrum", "sdlc", "waterfall", "uml", "pengujian", "black box", "white box"],
    "data mining": ["kdd", "association rule", "apriori", "fp-growth", "klastering", "k-means"],
    "cyber security": ["keamanan siber", "kriptografi", "aes", "rsa", "steganografi", "malware", "penetration testing"],
    "aes-256": ["aes", "kriptografi", "enkripsi", "cyber security"],
    "steganografi": ["lsb", "kriptografi", "watermarking", "cyber security"],
    "expert system": ["sistem pakar", "forward chaining", "backward chaining", "certainty factor", "dempster shafer"]
}
