KAMUS_EKSPANSI = {
    "artificial intelligence": [
        "ai",
        "artificial intelligence",
        "kecerdasan buatan",
        "machine intelligence",
        "intelligent system",
        "smart system",
        "generative ai",
        "genai",
        "llm",
        "large language model",
        "chatgpt",
        "gemini",
        "claude",
        "copilot",
        "artificial neural intelligence"
    ],

    "machine learning": [
        "machine learning",
        "ml",
        "deep learning",
        "supervised learning",
        "unsupervised learning",
        "reinforcement learning",
        "classification",
        "regression",
        "prediction",
        "forecasting",
        "clustering",
        "feature engineering",
        "feature selection",
        "model training",
        "model evaluation",
        "predictive analytics"
    ],

    "deep learning": [
        "deep learning",
        "cnn",
        "convolutional neural network",
        "rnn",
        "gru",
        "lstm",
        "transformer",
        "bert",
        "mobilenet",
        "mobilenetv2",
        "resnet",
        "efficientnet",
        "vision transformer",
        "gan",
        "autoencoder"
    ],

    "computer vision": [
        "computer vision",
        "vision",
        "image processing",
        "image recognition",
        "image classification",
        "image segmentation",
        "object detection",
        "face recognition",
        "facial recognition",
        "ocr",
        "optical character recognition",
        "biometric",
        "biometrik",
        "opencv",
        "yolo",
        "visual inspection",
        "mask detection",
        "anomaly detection"
    ],

    "natural language processing": [
        "nlp",
        "natural language processing",
        "text mining",
        "text processing",
        "text similarity",
        "semantic similarity",
        "semantic search",
        "embedding",
        "sentence transformer",
        "bert",
        "word2vec",
        "fasttext",
        "tf-idf",
        "bag of words",
        "tokenization",
        "stemming",
        "lemmatization",
        "stopword",
        "chatbot",
        "sentiment analysis",
        "text classification",
        "topic modeling",
        "prompt engineering"
    ],

    "software engineering": [
        "software engineering",
        "software development",
        "software architecture",
        "application development",
        "system development",
        "clean code",
        "clean architecture",
        "solid",
        "design pattern",
        "oop",
        "mvc",
        "microservice",
        "microservices",
        "rest api",
        "api gateway",
        "agile",
        "scrum",
        "waterfall",
        "prototype"
    ],

    "web development": [
        "website",
        "web",
        "web application",
        "frontend",
        "backend",
        "fullstack",
        "laravel",
        "django",
        "flask",
        "fastapi",
        "spring boot",
        "quarkus",
        "nestjs",
        "express",
        "react",
        "vue",
        "vuejs",
        "angular",
        "next.js",
        "nextjs",
        "codeigniter",
        "php",
        "javascript",
        "typescript"
    ],

    "mobile development": [
        "android",
        "ios",
        "flutter",
        "dart",
        "kotlin",
        "react native",
        "mobile application",
        "mobile app",
        "apk",
        "progressive web app",
        "pwa"
    ],

    "database": [
        "database",
        "dbms",
        "mysql",
        "postgresql",
        "mariadb",
        "mongodb",
        "firebase",
        "supabase",
        "redis",
        "sqlite",
        "sql server",
        "oracle",
        "nosql",
        "sql",
        "erd",
        "normalisasi",
        "query optimization"
    ],

    "networking": [
        "network",
        "networking",
        "computer network",
        "tcp/ip",
        "routing",
        "switching",
        "vpn",
        "lan",
        "wan",
        "wifi",
        "mikrotik",
        "cisco",
        "firewall",
        "dns",
        "dhcp",
        "ftth",
        "fiber optic"
    ],

    "cyber security": [
        "cyber security",
        "keamanan siber",
        "information security",
        "security",
        "penetration testing",
        "pentest",
        "ethical hacking",
        "vulnerability assessment",
        "nist",
        "iso 27001",
        "kami",
        "siem",
        "wazuh",
        "snort",
        "suricata",
        "malware",
        "trojan",
        "ransomware",
        "phishing",
        "threat intelligence",
        "incident response"
    ],

    "cloud computing": [
        "cloud",
        "cloud computing",
        "aws",
        "amazon web services",
        "azure",
        "google cloud",
        "gcp",
        "docker",
        "docker compose",
        "kubernetes",
        "terraform",
        "ansible",
        "virtual machine",
        "virtualization",
        "container"
    ],

    "devops": [
        "devops",
        "ci",
        "cd",
        "ci/cd",
        "pipeline",
        "deployment",
        "automation",
        "jenkins",
        "github actions",
        "gitlab ci",
        "monitoring"
    ],

    "internet of things": [
        "iot",
        "internet of things",
        "arduino",
        "esp32",
        "esp8266",
        "raspberry pi",
        "sensor",
        "mqtt",
        "lorawan",
        "smart monitoring",
        "smart parking",
        "embedded system"
    ],

    "robotics": [
        "robot",
        "robotics",
        "automation",
        "robot control",
        "control system",
        "embedded control"
    ],

    "ui ux": [
        "ui",
        "ux",
        "user interface",
        "user experience",
        "design thinking",
        "wireframe",
        "prototype",
        "figma",
        "usability",
        "sus",
        "ueq"
    ],

    "multimedia": [
        "multimedia",
        "motion graphic",
        "motion graphics",
        "animation",
        "animasi",
        "2d",
        "3d",
        "video editing",
        "company profile",
        "branding",
        "digital content",
        "graphic design"
    ],

    "game development": [
        "game",
        "game development",
        "unity",
        "unity3d",
        "unity2d",
        "gamification",
        "virtual reality",
        "vr",
        "augmented reality",
        "ar",
        "metaverse"
    ],

    "information system": [
        "sistem informasi",
        "information system",
        "management information system",
        "erp",
        "crm",
        "hris",
        "inventory",
        "asset management",
        "helpdesk",
        "warehouse",
        "attendance",
        "payroll",
        "procurement",
        "dashboard",
        "monitoring system",
        "document management",
        "reporting system"
    ],

    "decision support system": [
        "decision support system",
        "dss",
        "spk",
        "sistem pendukung keputusan",
        "ahp",
        "saw",
        "moora",
        "topsis",
        "weighted product",
        "electre",
        "promethee",
        "roc"
    ],

    "recommendation system": [
        "recommendation system",
        "recommender system",
        "recommendation engine",
        "content based filtering",
        "collaborative filtering",
        "hybrid recommendation",
        "cosine similarity",
        "semantic similarity"
    ],

    "blockchain": [
        "blockchain",
        "distributed ledger",
        "smart contract",
        "web3",
        "cryptocurrency"
    ],

    "data science": [
        "data science",
        "data mining",
        "data analytics",
        "business intelligence",
        "knowledge discovery",
        "eda",
        "exploratory data analysis",
        "pca",
        "visualization"
    ]
}